### ISSUE TITLE
build过程中报错：invalid conversion from 'uint16_t*' {aka 'short unsigned int*'} to 'int16_t*' {aka 'short int*'} [-fpermissive]

### ISSUE THREAD

**Issue by jhnmyr233** [physicsexpert/Exlink_Tool#1]
该方程定义的两个参数中后一个为指针类型，count变量声明为uint16_t类型，在使用&count取址时编译器报错。
但我将count变量的声明类型改为int16_t后，编译成功，没有报错。
由于我是c语言新手，对指针的使用非常生疏，希望能得到指点。
![main cpp - 无标题 (工作区) - Visual Studio Code 2024_11_2 19_41_54](https://github.com/user-attachments/assets/ff9efc4d-a1cc-401e-a5ec-b2241138a900)

**Comment by physicsexpert** [comment]
我这里是没有报错的，你检查一下函数的定义是不是和我这里一样
![QQ20241103-215937](https://github.com/user-attachments/assets/22d463a2-e6df-4200-b678-538d596bd520)

**Comment by jhnmyr233** [comment]
重新声明了一下，已解决，感谢😊
